name: Orders
form: $/shohabbos/stores/models/order/fields.yaml
modelClass: Shohabbos\Stores\Models\Order
defaultRedirect: shohabbos/stores/orders
create:
    redirect: 'shohabbos/stores/orders/update/:id'
    redirectClose: shohabbos/stores/orders
update:
    redirect: shohabbos/stores/orders
    redirectClose: shohabbos/stores/orders
