list: $/shohabbos/stores/models/order/columns.yaml
modelClass: Shohabbos\Stores\Models\Order
title: Orders
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'shohabbos/stores/orders/update/:id'
