list: $/shohabbos/stores/models/store/columns.yaml
modelClass: Shohabbos\Stores\Models\Store
title: Stores
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'shohabbos/stores/stores/update/:id'
